# Generated by Django 3.0.2 on 2020-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0003_care'),
    ]

    operations = [
        migrations.RenameField(
            model_name='care',
            old_name='first_name',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='care',
            old_name='last_name',
            new_name='name',
        ),
    ]
