# Generated by Django 3.0.2 on 2020-01-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0004_auto_20200126_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='noname', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='stable', max_length=100),
        ),
        migrations.DeleteModel(
            name='Care',
        ),
    ]
